import type { AppUser, Caso } from '@mesa-servicio/shared'

export const MOCK_USER: AppUser = {
  id: 'mock-user-001',
  name: 'María González',
  email: 'maria@seguros-xyz.cl',
  role: 'solicitante',
  companyId: 'emp-001',
  companyName: 'Seguros Generales XYZ SpA',
}

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()
const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000).toISOString()

export const MOCK_CASOS: Caso[] = [
  {
    id: 'caso-001',
    caseNumber: 'CASO-2026-001',
    title: 'Análisis pérdida total vehículo Toyota Yaris — Póliza P-2024-45678',
    description: 'Solicito análisis de pérdida total para vehículo Toyota Yaris 2022 patente BCDF-12, involucrado en accidente el 15/05/2026. Adjunto informe pericial.',
    typeId: 'perdida_total',
    typeName: 'Análisis de Pérdida Total',
    status: 'en_proceso',
    priority: 'alta',
    companyId: 'emp-001',
    companyName: 'Seguros Generales XYZ SpA',
    contactName: 'María González',
    contactEmail: 'maria@seguros-xyz.cl',
    assignedTo: 'Ana Rodríguez',
    assignedToEmail: 'a.rodriguez@falabella.cl',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    slaDeadline: daysFromNow(1),
    attachments: [
      { id: 'att-001', filename: 'informe_pericial_BCDF12.xlsx', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', sizeBytes: 12340, uploadedAt: daysAgo(4), uploadedBy: 'maria@seguros-xyz.cl' },
    ],
    history: [
      { id: 'log-001', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(4) },
      { id: 'log-002', previousStatus: 'nuevo', newStatus: 'en_proceso', changedBy: 'Ana Rodríguez', changedByEmail: 'a.rodriguez@falabella.cl', changedAt: daysAgo(3), comment: 'Asignado para revisión. Solicitando información al área de siniestros.' },
    ],
  },
  {
    id: 'caso-002',
    caseNumber: 'CASO-2026-002',
    title: 'Solicitud endoso póliza hogar — incorporación nuevo bien',
    description: 'Requiero endoso de póliza N° POL-2023-88901 para incorporar notebook + equipos electrónicos valorados en $850.000.',
    typeId: 'solicitud_documentos',
    typeName: 'Solicitud de Documentos',
    status: 'nuevo',
    priority: 'normal',
    companyId: 'emp-001',
    companyName: 'Seguros Generales XYZ SpA',
    contactName: 'María González',
    contactEmail: 'maria@seguros-xyz.cl',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    slaDeadline: daysFromNow(4),
    attachments: [],
    history: [
      { id: 'log-003', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(1) },
    ],
  },
  {
    id: 'caso-003',
    caseNumber: 'CASO-2026-003',
    title: 'Grabación llamada atención cliente 12/05/2026 — reclamo formal',
    description: 'Solicito grabación de llamada del 12/05/2026 a las 14:32 hrs desde número 562-2345-6789 para respaldo de reclamo.',
    typeId: 'solicitud_grabaciones',
    typeName: 'Solicitud de Grabaciones',
    status: 'resuelto',
    priority: 'normal',
    companyId: 'emp-001',
    companyName: 'Seguros Generales XYZ SpA',
    contactName: 'María González',
    contactEmail: 'maria@seguros-xyz.cl',
    assignedTo: 'Carlos Vega',
    assignedToEmail: 'c.vega@falabella.cl',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
    slaDeadline: daysAgo(5),
    resolvedAt: daysAgo(2),
    attachments: [],
    history: [
      { id: 'log-004', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(10) },
      { id: 'log-005', previousStatus: 'nuevo', newStatus: 'en_proceso', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(8), comment: 'Coordinando con equipo de grabaciones.' },
      { id: 'log-006', previousStatus: 'en_proceso', newStatus: 'resuelto', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(2), comment: 'Grabación enviada al correo del solicitante.' },
    ],
  },
  {
    id: 'caso-004',
    caseNumber: 'CASO-2026-004',
    title: 'Consulta devolución prima — cancelación anticipada SOAT',
    description: 'Consulta sobre estado de devolución de prima por cancelación anticipada de SOAT N° S-2025-77432.',
    typeId: 'consulta_devoluciones',
    typeName: 'Consulta de Devoluciones',
    status: 'cerrado',
    priority: 'normal',
    companyId: 'emp-001',
    companyName: 'Seguros Generales XYZ SpA',
    contactName: 'María González',
    contactEmail: 'maria@seguros-xyz.cl',
    assignedTo: 'Carlos Vega',
    assignedToEmail: 'c.vega@falabella.cl',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(12),
    slaDeadline: daysAgo(15),
    resolvedAt: daysAgo(13),
    attachments: [],
    history: [
      { id: 'log-007', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(20) },
      { id: 'log-008', previousStatus: 'nuevo', newStatus: 'en_proceso', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(18) },
      { id: 'log-009', previousStatus: 'en_proceso', newStatus: 'resuelto', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(13), comment: 'Devolución procesada. Monto: $34.000 — se acreditará en 3-5 días hábiles.' },
      { id: 'log-010', previousStatus: 'resuelto', newStatus: 'cerrado', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(12) },
    ],
  },
]
