import type { Caso, CaseType, Empresa } from '@mesa-servicio/shared'
import { CASE_TYPES } from '@mesa-servicio/shared'

const now = new Date()
const daysAgo = (d: number) => new Date(now.getTime() - d * 86400000).toISOString()
const daysFromNow = (d: number) => new Date(now.getTime() + d * 86400000).toISOString()

export const mockEmpresas: Empresa[] = [
  { id: 'emp-001', name: 'Seguros Generales XYZ SpA', rut: '76.123.456-7', domain: 'seguros-xyz.cl', country: 'CL', active: true },
  { id: 'emp-002', name: 'Compañía de Seguros ABC S.A.', rut: '96.789.012-3', domain: 'seguros-abc.cl', country: 'CL', active: true },
  { id: 'emp-003', name: 'Reaseguros del Pacífico Perú', rut: '20123456789', domain: 'reaseguros-pacifico.pe', country: 'PE', active: true },
]

export const mockCasos: Caso[] = [
  {
    id: 'caso-001',
    caseNumber: 'CASO-2026-001',
    title: 'Análisis pérdida total vehículo Toyota Yaris — Póliza P-2024-45678',
    description: 'Solicito análisis de pérdida total para vehículo Toyota Yaris 2022 patente BCDF-12, involucrado en accidente el 15/05/2026. Adjunto informe pericial.',
    typeId: 'perdida_total',
    typeName: 'Análisis de Pérdida Total',
    status: 'en_proceso',
    priority: 'alta',
    companyId: 'emp-001',
    companyName: 'Seguros Generales XYZ SpA',
    contactName: 'Carolina Fuentes',
    contactEmail: 'c.fuentes@seguros-xyz.cl',
    assignedTo: 'Ana Rodríguez',
    assignedToEmail: 'a.rodriguez@falabella.cl',
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    slaDeadline: daysFromNow(1),
    attachments: [
      { id: 'att-001', filename: 'informe_pericial_BCDF12.xlsx', contentType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', sizeBytes: 12340, uploadedAt: daysAgo(4), uploadedBy: 'c.fuentes@seguros-xyz.cl' },
    ],
    history: [
      { id: 'log-001', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(4) },
      { id: 'log-002', previousStatus: 'nuevo', newStatus: 'en_proceso', changedBy: 'Ana Rodríguez', changedByEmail: 'a.rodriguez@falabella.cl', changedAt: daysAgo(3), comment: 'Asignado para revisión. Solicitando información adicional al área de siniestros.' },
    ],
  },
  {
    id: 'caso-002',
    caseNumber: 'CASO-2026-002',
    title: 'Solicitud endoso póliza hogar — incorporación nuevo bien',
    description: 'Requiero endoso de póliza N° POL-2023-88901 para incorporar nuevo bien (notebook + equipos electrónicos) valorados en $850.000.',
    typeId: 'solicitud_documentos',
    typeName: 'Solicitud de Documentos',
    status: 'nuevo',
    priority: 'normal',
    companyId: 'emp-001',
    companyName: 'Seguros Generales XYZ SpA',
    contactName: 'Roberto Sánchez',
    contactEmail: 'r.sanchez@seguros-xyz.cl',
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
    slaDeadline: daysFromNow(4),
    attachments: [],
    history: [
      { id: 'log-003', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(1) },
    ],
  },
  {
    id: 'caso-003',
    caseNumber: 'CASO-2026-003',
    title: 'Grabación llamada atención cliente 12/05/2026 — reclamo',
    description: 'Solicito grabación de llamada realizada el 12/05/2026 a las 14:32 hrs desde el número 562-2345-6789 para respaldo de reclamo formal.',
    typeId: 'solicitud_grabaciones',
    typeName: 'Solicitud de Grabaciones',
    status: 'resuelto',
    priority: 'normal',
    companyId: 'emp-002',
    companyName: 'Compañía de Seguros ABC S.A.',
    contactName: 'Daniela Morales',
    contactEmail: 'd.morales@seguros-abc.cl',
    assignedTo: 'Carlos Vega',
    assignedToEmail: 'c.vega@falabella.cl',
    createdAt: daysAgo(10),
    updatedAt: daysAgo(2),
    slaDeadline: daysAgo(5),
    resolvedAt: daysAgo(2),
    attachments: [],
    history: [
      { id: 'log-004', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(10) },
      { id: 'log-005', previousStatus: 'nuevo', newStatus: 'en_proceso', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(8), comment: 'Coordinando con equipo de grabaciones.' },
      { id: 'log-006', previousStatus: 'en_proceso', newStatus: 'resuelto', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(2), comment: 'Grabación enviada al correo del solicitante.' },
    ],
  },
  {
    id: 'caso-004',
    caseNumber: 'CASO-2026-004',
    title: 'Solicitud baja póliza vida individual — cliente fallecido',
    description: 'Solicitud de baja de póliza de vida individual N° PV-2021-33210 por fallecimiento del asegurado. Adjuntamos certificado de defunción.',
    typeId: 'solicitud_baja',
    typeName: 'Solicitud de Baja',
    status: 'escalado',
    priority: 'alta',
    companyId: 'emp-002',
    companyName: 'Compañía de Seguros ABC S.A.',
    contactName: 'Martín Pérez',
    contactEmail: 'm.perez@seguros-abc.cl',
    assignedTo: 'Ana Rodríguez',
    assignedToEmail: 'a.rodriguez@falabella.cl',
    createdAt: daysAgo(6),
    updatedAt: daysAgo(0),
    slaDeadline: daysFromNow(-1),
    attachments: [
      { id: 'att-002', filename: 'certificado_defuncion.pdf', contentType: 'application/pdf', sizeBytes: 185420, uploadedAt: daysAgo(6), uploadedBy: 'm.perez@seguros-abc.cl' },
    ],
    history: [
      { id: 'log-007', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(6) },
      { id: 'log-008', previousStatus: 'nuevo', newStatus: 'en_proceso', changedBy: 'Ana Rodríguez', changedByEmail: 'a.rodriguez@falabella.cl', changedAt: daysAgo(5) },
      { id: 'log-009', previousStatus: 'en_proceso', newStatus: 'escalado', changedBy: 'Ana Rodríguez', changedByEmail: 'a.rodriguez@falabella.cl', changedAt: daysAgo(1), comment: 'Escalado a área legal por requerir validación adicional de documentación.' },
    ],
  },
  {
    id: 'caso-005',
    caseNumber: 'CASO-2026-005',
    title: 'Consulta devolución prima — cancelación anticipada SOAT',
    description: 'Consulta sobre estado de devolución de prima proporcional por cancelación anticipada de SOAT N° S-2025-77432 con fecha efectiva 01/04/2026.',
    typeId: 'consulta_devoluciones',
    typeName: 'Consulta de Devoluciones',
    status: 'cerrado',
    priority: 'normal',
    companyId: 'emp-003',
    companyName: 'Reaseguros del Pacífico Perú',
    contactName: 'Lucía Vargas',
    contactEmail: 'l.vargas@reaseguros-pacifico.pe',
    assignedTo: 'Carlos Vega',
    assignedToEmail: 'c.vega@falabella.cl',
    createdAt: daysAgo(20),
    updatedAt: daysAgo(12),
    slaDeadline: daysAgo(15),
    resolvedAt: daysAgo(13),
    attachments: [],
    history: [
      { id: 'log-010', previousStatus: null, newStatus: 'nuevo', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(20) },
      { id: 'log-011', previousStatus: 'nuevo', newStatus: 'en_proceso', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(18) },
      { id: 'log-012', previousStatus: 'en_proceso', newStatus: 'resuelto', changedBy: 'Carlos Vega', changedByEmail: 'c.vega@falabella.cl', changedAt: daysAgo(13), comment: 'Devolución procesada. Monto: S/ 340.00 — se acreditará en 3-5 días hábiles.' },
      { id: 'log-013', previousStatus: 'resuelto', newStatus: 'cerrado', changedBy: 'Sistema', changedByEmail: 'sistema@mesa.cl', changedAt: daysAgo(12), comment: 'Cerrado automáticamente 24h después de resolución sin respuesta del solicitante.' },
    ],
  },
]

export const mockCaseTypes: CaseType[] = CASE_TYPES
